#!/bin/bash -xe

[ -f defaults ] && source defaults
[ -f .secrets ] && source .secrets

cat << EOF > ${PACKER_CONFIG_DIR?}/config.json
{
  "host_name": "${BUILD_OS_HOSTNAME?}",
  "user_name": "${BUILD_OS_USER?}",
  "user_password": "${BUILD_OS_USER_PASS?}"
}
EOF
