# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "distro_url" {
  type    = string
  default = "https://distro.libre.computer/ci/raspbian/11/2022-09-22-raspbian-bullseye-arm64+roc-rk3328-cc.img.xz"
}

variable "host_name" {
  type    = string
  default = "netmaster"
}

variable "user_name" {
  default = env("BUILD_OS_USER")
}

variable "user_password" {
  default   = env("BUILD_OS_USER_PASS")
  sensitive = true
}

variable "image_file_name" {
  type      = string
  default   = "netmaster.img"
  sensitive = true
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "arm" "rk3328_rapsbian" {
  file_checksum_type    = "sha256"
  file_checksum_url     = "https://distro.libre.computer/ci/raspbian/11/SHA256SUMS"
  file_target_extension = "xz"
  file_unarchive_cmd    = ["xz", "--decompress", "$ARCHIVE_PATH"]
  file_urls             = ["${var.distro_url}"]
  image_build_method    = "reuse"
  image_chroot_env      = ["PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"]
  image_partitions {
    filesystem   = "fat"
    mountpoint   = "/boot/firmware"
    name         = "boot"
    size         = "256M"
    start_sector = "2048"
    type         = "c"
  }
  image_partitions {
    filesystem   = "ext4"
    mountpoint   = "/"
    name         = "root"
    size         = "5.8G"
    start_sector = "526336"
    type         = "83"
  }
  image_path                   = "${var.image_file_name}"
  image_size                   = "6.2G"
  image_type                   = "dos"
  qemu_binary_destination_path = "/usr/bin/qemu-aarch64-static"
  qemu_binary_source_path      = "/usr/bin/qemu-aarch64-static"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.arm.rk3328_rapsbian"]

  provisioner "shell" {
    scripts = [
      "installIt.d/00-sanity-check",
      "installIt.d/10-raspbian-setup-default-user",
      "installIt.d/20-enable-ssh",
      "installIt.d/25-set-hostname",
      "installIt.d/45-install-docker",
      "installIt.d/99-sanity-check",
    ]
  }
}
