#!/bin/bash -xe

[ -f defaults ] && source defaults
[ -f .secrets ] && source .secrets

#sudo apt install -y git
#sudo apt install -y unzip
#sudo apt install -y qemu-user-static
#sudo apt install -y e2fsprogs
#sudo apt install -y dosfstools
#sudo apt install -y libarchive-tools # bsdtar

mkdir -p ${BUILDENV_BIN?}
mkdir -p ${BUILDENV_DOWNLOADS?}

#wget https://releases.hashicorp.com/packer/1.8.6/packer_1.8.6_linux_arm64.zip
wget -P ${BUILDENV_DOWNLOADS} ${BUILDENV_PACKER_REPO?}/${BUILDENV_PACKER_DISTRO?}
unzip -o ${BUILDENV_DOWNLOADS}/${BUILDENV_PACKER_DISTRO##*/} -d buildEnv/bin

docker pull mkaczanowski/packer-builder-arm:latest

curl -fsSL https://get.docker.com -o installIt.d/46-install-docker
chmod +x installIt.d/46-install-docker
