#!/bin/bash -e
#U
#U NAME
#U    Install Pihole using curl https://install.pi-hole.net
#U
#U SYNOPSIS
#U    50-install-pihole <pi_distro_mount_dir>
#U
#U DESCRIPTION
#U    pihole install
#U
#U OPTIONS
#U    
#U    pi_distro_mount_dir|[DEFAULT_PI_DISTRO_MOUNT_DIR] - image mount point directory
#U
#
function usage() {
# usage - Any comment in script starting with '#U' will show up in "usage"
  egrep "^#U" $0 | sed -e 's/^#U //g' -e 's/^#U//g'
  exit 1
}

pi_distro_mount_dir=${1:-${DEFAULT_PI_DISTRO_MOUNT_DIR?"$(usage)"}}

#
# https://discourse.pi-hole.net/t/what-is-setupvars-conf-and-how-do-i-use-it/3533
#
mkdir -p /etc/pihole
echo ----------------------------
echo /etc/pihole/setupVars.conf
cat << EOF | tee /etc/pihole/setupVars.conf
WEBPASSWORD=$(echo -n ${BUILD_OS_USER_PASS?} | sha256sum | awk '{printf "%s",$1 }' | sha256sum | awk '{print $1}')
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=192.168.100.12/32
#IPV6_ADDRESS=2601:444:8111:403:55d6:2f11:41bf:13bb
IPV6_ADDRESS=
QUERY_LOGGING=true
INSTALL_WEB=true
DNSMASQ_LISTENING=single
PIHOLE_DNS_1=208.67.222.222
PIHOLE_DNS_2=208.67.220.220
PIHOLE_DNS_3=2620:0:ccc::2
PIHOLE_DNS_4=2620:0:ccd::2
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=true
TEMPERATUREUNIT=C
WEBUIBOXEDLAYOUT=traditional
API_EXCLUDE_DOMAINS=
API_EXCLUDE_CLIENTS=
API_QUERY_LOG_SHOW=all
API_PRIVACY_MODE=false
EOF
echo ----------------------------

curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
